In [1]:
import numpy as np
import scipy.linalg
import time

# Define matrix A and vector b with consistent dimensions
A = np.array([[2, 1, 3],
              [4, 4, 6],
              [9, 8, 7]])

b = np.array([2, 3, 1]).reshape(-1, 1) 

# Method 1:
try:
    x1 = np.linalg.solve(A, b)
    r1 = np.dot(A, x1) - b
    print("\nSolution vector x1 (using solve):")
    print(x1)
    print("\nResidual vector r1:")
    print(r1)
except np.linalg.LinAlgError:
    print("Matrix A is singular or not square, using alternative methods.")

# Method 2:
P, L, U = scipy.linalg.lu(A)
x2 = np.linalg.lstsq(A, b, rcond=None)[0]
r2 = np.dot(A, x2) - b

print("\nMatrix P (Permutation matrix):", P)
print("\nMatrix L (Lower triangular matrix):", L)
print("\nMatrix U (Upper triangular matrix):", U)
print("\nSolution vector x2 (using least squares):", x2)
print("\nResidual vector r2:", r2)

# Method 3:
A_pinv = np.linalg.pinv(A)
y = np.dot(A_pinv, b)
r3 = np.dot(A, y) - b

print("\nSolution vector y (from pseudoinverse):")
print(y)
print("\nResidual vector r3:")
print(r3)

# Method 4: Reduced Row Echelon Form (RREF)
def rref(A):
    A = A.astype(float)
    m, n = A.shape
    lead = 0
    for r in range(m):
        if lead >= n:
            break
        if A[r, lead] == 0:
            for i in range(r + 1, m):
                if A[i, lead] != 0:
                    A[[r, i]] = A[[i, r]]
                    break
        if A[r, lead] != 0:
            A[r] = A[r] / A[r, lead]
            for i in range(m):
                if i != r:
                    A[i] = A[i] - A[i, lead] * A[r]
        lead += 1
    return A

C = np.hstack((A, b))
R = rref(C)
x3 = R[:, -1]
r4 = np.dot(A, x3) - b

print("\nSolution vector x3 (from RREF):")
print(x3)
print("\nResidual vector r4:")
print(r4)

# Timing different methods
start_time = time.time()
x1 = np.linalg.lstsq(A, b, rcond=None)[0]
time_lstsq = time.time() - start_time

start_time = time.time()
y = np.dot(A_pinv, b)
time_pinv = time.time() - start_time

start_time = time.time()
C = np.hstack((A, b))
R = rref(C)
x3 = R[:, -1]
time_rref = time.time() - start_time

print("\nComputational times:")
print(f"Least squares: {time_lstsq} seconds")
print(f"Pseudoinverse: {time_pinv} seconds")
print(f"Reduced row echelon form (RREF): {time_rref} seconds")


Solution vector x1 (using solve):
[[-0.19230769]
 [-0.5       ]
 [ 0.96153846]]

Residual vector r1:
[[0.]
 [0.]
 [0.]]

Matrix P (Permutation matrix): [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Matrix L (Lower triangular matrix): [[ 1.          0.          0.        ]
 [ 0.22222222  1.          0.        ]
 [ 0.44444444 -0.57142857  1.        ]]

Matrix U (Upper triangular matrix): [[ 9.          8.          7.        ]
 [ 0.         -0.77777778  1.44444444]
 [ 0.          0.          3.71428571]]

Solution vector x2 (using least squares): [[-0.19230769]
 [-0.5       ]
 [ 0.96153846]]

Residual vector r2: [[1.33226763e-15]
 [2.66453526e-15]
 [8.88178420e-16]]

Solution vector y (from pseudoinverse):
[[-0.19230769]
 [-0.5       ]
 [ 0.96153846]]

Residual vector r3:
[[ 8.88178420e-16]
 [-1.33226763e-15]
 [-8.88178420e-16]]

Solution vector x3 (from RREF):
[-0.19230769 -0.5         0.96153846]

Residual vector r4:
[[ 0.  1. -1.]
 [-1.  0. -2.]
 [ 1.  2.  0.]]

Computational times:
Least squ