In [2]:
!pip install opencv-python

  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/a4/7d/f1c30a92854540bf789e9cd5dde7ef49bbe63f855b85a2e6b3db8135c591/opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl.metadata
   ---------------------------------------- 0.0/39.5 MB ? eta -:--:--
   ---------------------------------------- 0.2/39.5 MB 3.9 MB/s eta 0:00:11
    --------------------------------------- 0.5/39.5 MB 6.7 MB/s eta 0:00:06
    --------------------------------------- 1.0/39.5 MB 6.7 MB/s eta 0:00:06
   - -------------------------------------- 1.3/39.5 MB 7.7 MB/s eta 0:00:05
   - -------------------------------------- 1.8/39.5 MB 7.5 MB/s eta 0:00:06
   -- ------------------------------------- 2.2/39.5 MB 7.7 MB/s eta 0:00:05
   -- ------------------------------------- 2.5/39.5 MB 7.7 MB/s eta 0:00:05
   -- ------------------------------------- 2.9/39.5 MB 8.1 MB/s eta 0:00:05
   --- ------------------------------------ 3.3/39.5 MB 7.8 MB/s eta 0:00:05
   --- --------

In [3]:
import numpy as np
import imageio.v2 as imageio
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import scipy.linalg

PROJECT 1

In [7]:
# 1. Determine the length of a matrix or vector
A = np.array([[2, 8, 9],
              [3, 3, 1],
              [4, 0, 15]])

print("Matrix A:\n", A)
print("Length of A:", len(A))

Matrix A:
 [[ 2  8  9]
 [ 3  3  1]
 [ 4  0 15]]
Length of A: 3


In [8]:
# 2. Add B as the fourth row of A to create C
B = np.array([[1, 1, 1]]) 
C = np.vstack((A, B))
print("\nMatrix B:\n", B)
print("\nMatrix C:\n", C)


Matrix B:
 [[1 1 1]]

Matrix C:
 [[ 2  8  9]
 [ 3  3  1]
 [ 4  0 15]
 [ 1  1  1]]


In [9]:
# 3. Create D from rows 2, 3, 4 and columns 3, 4 of C
D = C[1:4, 1:3]
print("\nMatrix D:\n", D)


Matrix D:
 [[ 3  1]
 [ 0 15]
 [ 1  1]]


In [10]:
# 4. Transpose D to create E
E = D.T
print("\nMatrix E:\n", E)

# 5. Check the size of E
print("Size of E:", E.shape)


Matrix E:
 [[ 3  0  1]
 [ 1 15  1]]
Size of E: (2, 3)


In [11]:
# 6. Create equally spaced vectors
print("\nEqually spaced vector:", np.linspace(1, 2, 9))


Equally spaced vector: [1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


In [16]:
# 7 & 8. Find max and min values in each column and row of A
print("\nMatrix A:\n",A)
print("\nMax in each column:", np.max(A, axis=0))
print("Min in each column:", np.min(A, axis=0))
print("Min in each row:", np.min(A, axis=1))
print("Max in each row:", np.max(A, axis=1))


Matrix A:
 [[ 2  8  9]
 [ 3  3  1]
 [ 4  0 15]]

Max in each column: [ 4  8 15]
Min in each column: [2 0 1]
Min in each row: [2 1 0]
Max in each row: [ 9  3 15]


In [15]:
# 9. Calculate mean and sum in each column and row of A
print("\nMean of each column:", np.mean(A, axis=0))
print("Sum of each col:", np.sum(A, axis=1))
print("Mean of each row:", np.mean(A, axis=1))
print("Sum of each row:", np.sum(A, axis=1))


Mean of each column: [3.         3.66666667 8.33333333]
Sum of each col: [19  7 19]
Mean of each row: [6.33333333 2.33333333 6.33333333]
Sum of each row: [19  7 19]


In [13]:
# 10 & 11. Create random matrices F and G
F = np.array([[4, 1, 6],
              [1, 2, 5],
              [3, 8, 4]])

G = np.array([[5, 1, 0],
              [2, 1, 4],
              [2, 4, 1]])

print("\nMatrix F:\n", F)
print("Matrix G:\n", G)

print("\nF * 2:\n", F * 2)
print("F + G:\n", F + G)
print("F - G:\n", F - G)
print("Element-wise multiplication:\n", np.multiply(F, G))


Matrix F:
 [[4 1 6]
 [1 2 5]
 [3 8 4]]
Matrix G:
 [[5 1 0]
 [2 1 4]
 [2 4 1]]

F * 2:
 [[ 8  2 12]
 [ 2  4 10]
 [ 6 16  8]]
F + G:
 [[ 9  2  6]
 [ 3  3  9]
 [ 5 12  5]]
F - G:
 [[-1  0  6]
 [-1  1  1]
 [ 1  4  3]]
Element-wise multiplication:
 [[20  1  0]
 [ 2  2 20]
 [ 6 32  4]]


In [14]:
#12.Matrix multiplication (F * A)
if F.shape[1] == A.shape[0]:
    print("\nMatrix Multiplication F * A:\n", np.dot(F, A))
else:
    print("\nMatrix multiplication is not possible due to shape mismatch.")


Matrix Multiplication F * A:
 [[ 35  35 127]
 [ 28  14  86]
 [ 46  48  95]]


In [17]:
#13.Generate special matrices
print("\nIdentity Matrix:\n", np.eye(3))
print("Zero Matrix:\n", np.zeros((5, 3)))
print("One Matrix:\n", np.ones((4, 2)))
S = np.diag([2, 1, 7])
print("Diagonal Matrix S:\n", S)
R = np.random.randint(1, 10, (6, 6))
print("Extracted Diagonal:", np.diag(R))


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Diagonal Matrix S:
 [[2 0 0]
 [0 1 0]
 [0 0 7]]
Extracted Diagonal: [5 6 7 8 9 7]
